"""added role requirements table properly

Revision ID: 04823737aee5
Revises: c3b86e6b3501
Create Date: 2026-01-11 20:45:18.382745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04823737aee5'
down_revision: Union[str, Sequence[str], None] = 'c3b86e6b3501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('end_time_local', sa.Time(), nullable=False),
    sa.Column('requires_manager', sa.Boolean(), nullable=False),
    sa.Column('requires_keyholder', sa.Boolean(), nullable=False),
    sa.Column('min_manager_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_modified_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'department_id', 'day_of_week', 'start_time_local', 'end_time_local', name='uix_role_requirements_unique_timeslot')
    )
    op.create_index(op.f('ix_role_requirements_department_id'), 'role_requirements', ['department_id'], unique=False)
    op.create_index(op.f('ix_role_requirements_id'), 'role_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_role_requirements_store_id'), 'role_requirements', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_requirements_store_id'), table_name='role_requirements')
    op.drop_index(op.f('ix_role_requirements_id'), table_name='role_requirements')
    op.drop_index(op.f('ix_role_requirements_department_id'), table_name='role_requirements')
    op.drop_table('role_requirements')
    # ### end Alembic commands ###
