"""added ai outputs table

Revision ID: 1d007dc87c5c
Revises: 188ff3b5be2d
Create Date: 2026-02-05 19:50:40.933451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d007dc87c5c'
down_revision: Union[str, Sequence[str], None] = '188ff3b5be2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('affects_user_id', sa.Integer(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('COMPLETE', 'NEEDS_CLARIFICATION', 'INVALID', name='ai_output_status_enum'), server_default='COMPLETE', nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affects_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['input_id'], ['ai_inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_outputs_affects_user_id'), 'ai_outputs', ['affects_user_id'], unique=False)
    op.create_index(op.f('ix_ai_outputs_input_id'), 'ai_outputs', ['input_id'], unique=False)
    op.create_index(op.f('ix_ai_outputs_status'), 'ai_outputs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_inputs_req_by_user_id'), 'ai_inputs', ['req_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_inputs_req_by_user_id'), table_name='ai_inputs')
    op.drop_index(op.f('ix_ai_outputs_status'), table_name='ai_outputs')
    op.drop_index(op.f('ix_ai_outputs_input_id'), table_name='ai_outputs')
    op.drop_index(op.f('ix_ai_outputs_affects_user_id'), table_name='ai_outputs')
    op.drop_table('ai_outputs')
    # ### end Alembic commands ###
