"""added store operating hours

Revision ID: 5138c453f6c1
Revises: 368674234dcd
Create Date: 2026-03-21 15:05:19.976795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5138c453f6c1'
down_revision: Union[str, Sequence[str], None] = '368674234dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first so existing rows don't violate NOT NULL
    op.add_column('stores', sa.Column('opening_time', sa.Time(), nullable=True))
    op.add_column('stores', sa.Column('closing_time', sa.Time(), nullable=True))

    # Backfill existing rows with sensible defaults (07:00 / 22:00)
    op.execute("UPDATE stores SET opening_time = '07:00:00' WHERE opening_time IS NULL")
    op.execute("UPDATE stores SET closing_time = '22:00:00' WHERE closing_time IS NULL")

    # Now enforce NOT NULL
    op.alter_column('stores', 'opening_time', nullable=False)
    op.alter_column('stores', 'closing_time', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'closing_time')
    op.drop_column('stores', 'opening_time')
    # ### end Alembic commands ###
