"""added ai proposals table

Revision ID: 7d23bb5d061d
Revises: 1d007dc87c5c
Create Date: 2026-02-05 20:02:28.552954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d23bb5d061d'
down_revision: Union[str, Sequence[str], None] = '1d007dc87c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_output_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('AVAILABILITY', 'COVERAGE', 'ROLE_REQUIREMENT', 'LABOUR_BUDGET', name='proposal_type_enum'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='proposal_status_enum'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('last_actioned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_output_id'], ['ai_outputs.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['last_actioned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_proposals_ai_output_id'), 'ai_proposals', ['ai_output_id'], unique=False)
    op.create_index(op.f('ix_ai_proposals_department_id'), 'ai_proposals', ['department_id'], unique=False)
    op.create_index(op.f('ix_ai_proposals_last_actioned_by'), 'ai_proposals', ['last_actioned_by'], unique=False)
    op.create_index(op.f('ix_ai_proposals_status'), 'ai_proposals', ['status'], unique=False)
    op.create_index(op.f('ix_ai_proposals_store_id'), 'ai_proposals', ['store_id'], unique=False)
    op.add_column('ai_inputs', sa.Column('processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_inputs', 'processed')
    op.drop_index(op.f('ix_ai_proposals_store_id'), table_name='ai_proposals')
    op.drop_index(op.f('ix_ai_proposals_status'), table_name='ai_proposals')
    op.drop_index(op.f('ix_ai_proposals_last_actioned_by'), table_name='ai_proposals')
    op.drop_index(op.f('ix_ai_proposals_department_id'), table_name='ai_proposals')
    op.drop_index(op.f('ix_ai_proposals_ai_output_id'), table_name='ai_proposals')
    op.drop_table('ai_proposals')
    # ### end Alembic commands ###
