"""added shifts table

Revision ID: 7f6413c406ce
Revises: 1cdc2ab303a4
Create Date: 2026-01-07 18:08:10.385484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6413c406ce'
down_revision: Union[str, Sequence[str], None] = '1cdc2ab303a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', name='shift_status_enum'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'AI', 'IMPORT', name='shift_source_enum'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shifts_employee_start', 'shifts', ['employee_id', 'start_datetime_utc'], unique=False)
    op.create_index('ix_shifts_store_start', 'shifts', ['store_id', 'start_datetime_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shifts_store_start', table_name='shifts')
    op.drop_index('ix_shifts_employee_start', table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
