"""added labour budget table

Revision ID: c3696c474e17
Revises: 04823737aee5
Create Date: 2026-01-11 20:50:31.827204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3696c474e17'
down_revision: Union[str, Sequence[str], None] = '04823737aee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('budget_hours', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id', 'department_id'], ['store_departments.store_id', 'store_departments.department_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'department_id', 'week_start_date', name='uix_labour_budgets_unique_week')
    )
    op.create_index(op.f('ix_labour_budgets_department_id'), 'labour_budgets', ['department_id'], unique=False)
    op.create_index(op.f('ix_labour_budgets_id'), 'labour_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_labour_budgets_store_id'), 'labour_budgets', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labour_budgets_store_id'), table_name='labour_budgets')
    op.drop_index(op.f('ix_labour_budgets_id'), table_name='labour_budgets')
    op.drop_index(op.f('ix_labour_budgets_department_id'), table_name='labour_budgets')
    op.drop_table('labour_budgets')
    # ### end Alembic commands ###
