"""added coverage requirements table

Revision ID: fa19dcfc9357
Revises: 06a71a40a8ea
Create Date: 2026-01-11 20:25:13.950095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa19dcfc9357'
down_revision: Union[str, Sequence[str], None] = '06a71a40a8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=True),
    sa.Column('end_time_local', sa.Time(), nullable=True),
    sa.Column('min_staff', sa.Integer(), nullable=False),
    sa.Column('max_staff', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_modified_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id', 'department_id'], ['store_departments.store_id', 'store_departments.department_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'department_id', 'day_of_week', 'start_time_local', 'end_time_local', name='uix_coverage_requirements_unique_timeslot')
    )
    op.create_index(op.f('ix_coverage_requirements_department_id'), 'coverage_requirements', ['department_id'], unique=False)
    op.create_index(op.f('ix_coverage_requirements_id'), 'coverage_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_coverage_requirements_store_id'), 'coverage_requirements', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coverage_requirements_store_id'), table_name='coverage_requirements')
    op.drop_index(op.f('ix_coverage_requirements_id'), table_name='coverage_requirements')
    op.drop_index(op.f('ix_coverage_requirements_department_id'), table_name='coverage_requirements')
    op.drop_table('coverage_requirements')
    # ### end Alembic commands ###
